Pronia/Models/Size.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Size
    {
        public int Id { get; set; }
        [StringLength(maximumLength:10)]
        public string Name { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/SizeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class SizeController : Controller
    {
        private readonly AppDbContext _context;

        public SizeController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {


            List<Size> sizes = await _context.Sizes.ToListAsync();
            return View(sizes);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Size size)
        {
            if (!ModelState.IsValid) return View();

            await _context.Sizes.AddAsync(size);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int id)
        {
            Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
           
            return View(size);
        }
        public async Task<IActionResult> Edit(int id)
        {
            Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
            return View(size);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int id,Size size)
        {
            Size existedSize = await _context.Sizes.FirstOrDefaultAsync(s=>s.Id==id);
            if (existedSize == null) return NotFound();
            if (id != size.Id) return BadRequest();
            existedSize.Name = size.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Delete(int id)
        {
            Size size = await _context.Sizes.FirstOrDefaultAsync(s=>s.Id==id);
            if (size == null) return NotFound();

            return View(size);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSize(int id)
        {
            Size size = await _context.Sizes.FirstOrDefaultAsync(s => s.Id == id);
            if (size == null) return NotFound();
            _context.Sizes.Remove(size);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Size/Create.cshtml
@model Size
@{
    ViewData["Title"] = "Create";
}
<form method="post">
    <div>
        <label class="mb-3">Size name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Create size</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Size/Delete.cshtml
@model Size
@{
    ViewData["Title"] = "Delete";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Name: </h4>
        <p>
            @Model.Name
        </p>
    </div>
</div>
<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Pronia/Areas/ProniaAdmin/Views/Size/Detail.cshtml
@model Size
@{
    ViewData["Title"] = "Detail";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Name: </h4>
        <p>
            @Model.Name
        </p>
    </div>
</div>

Pronia/Areas/ProniaAdmin/Views/Size/Edit.cshtml
@model Size
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div>
        <label class="mb-3">Size name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Edit size</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Size/Index.cshtml
@model List<Size>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a asp-controller="size" asp-action="create" style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create size</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Size size in Model)
            {
                <tr>
                    <td>
                        @size.Id
                    </td>
                    <td>
                        @size.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Size" asp-action="Detail" asp-route-id="@size.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="ms-2 edit">
                                <a asp-controller="Size" asp-action="Edit" asp-route-id="@size.Id" class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                            </div>
                            <div class="ms-2 delete">
                                <a asp-controller="Size" asp-action="Delete" asp-route-id="@size.Id" class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>