Pronia/Models/Color.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Color
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<Plant> Plants { get; set; }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Models;
using Pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class ColorController : Controller
    {
        private readonly AppDbContext _context;

        public ColorController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            List<Color> colors = await _context.Colors.ToListAsync();
            return View(colors);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Color color)
        {
            if (!ModelState.IsValid) return View();

            await _context.Colors.AddAsync(color);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int id)
        {
            Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();

            return View(color);
        }
        public async Task<IActionResult> Edit(int id)
        {
            Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            return View(color);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,Color color)
        {
            Color existedColor = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (existedColor == null) return NotFound();
            if (id != color.Id) return BadRequest();
            existedColor.Name = color.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {

            Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            return View(color);
        }
        [HttpPost]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteColor(int id)
        {
            Color color = await _context.Colors.FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();
            _context.Colors.Remove(color);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Color/Create.cshtml
@model Color
@{
    ViewData["Title"] = "Create";
}

<form method="post">
    <div>
        <label class="mb-3">Color name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Create color</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Color/Delete.cshtml
@model Color
@{
    ViewData["Title"] = "Delete";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Name: </h4>
        <p>
            @Model.Name
        </p>
    </div>
</div>
<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Pronia/Areas/ProniaAdmin/Views/Color/Detail.cshtml
@model Color
@{
    ViewData["Title"] = "Detail";
}
<div>
<div>
    <h4>Id: </h4>
    <p>
        @Model.Id
    </p>
</div>
<div>
    <h4>Name: </h4>
    <p>
        @Model.Name
    </p>
</div>
</div>

Pronia/Areas/ProniaAdmin/Views/Color/Edit.cshtml
@model Color
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div>
        <label class="mb-3">Color name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Edit color</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a asp-controller="Color" asp-action="Create" style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create size</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Color color in Model)
            {
                <tr>
                    <td>
                        @color.Id
                    </td>
                    <td>
                        @color.Name
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Color" asp-action="Detail" asp-route-id="@color.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="ms-2 edit">
                                <a asp-controller="Color" asp-action="Edit" asp-route-id="@color.Id" class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                            </div>
                            <div class="ms-2 delete">
                                <a asp-controller="Color" asp-action="Delete" asp-route-id="@color.Id" class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>