Pronia/Models/Plant.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Plant
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Column(TypeName = "decimal(6,2)")]
        public decimal Price { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string SKUCode { get; set; }
        [Required]
        public string Shipping { get; set; }
        [Required]
        public string Request { get; set; }
        [Required]
        public string Guarantee { get; set; }
        public int? ColorId { get; set; }
        public Color Color { get; set; }
        public int? SizeId { get; set; }
        public Size Size { get; set; }
        public List<PlantImage> PlantImages { get; set; }
        public List<PlantCategory> PlantCategories { get; set; }
        [NotMapped]
        public IFormFile MainImage { get; set; }
        [NotMapped]
        public List<IFormFile> AnotherImages { get; set; }
        [NotMapped]
        public int? ImageId { get; set; }
        [NotMapped]
        public List<int> ImageIds { get; set; }
        [NotMapped]
        public List<int> CategoryIds { get; set; }


    }
}

Pronia/Areas/ProniaAdmin/Controllers/PlantController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Extensions;
using Pronia.Models;
using Pronia.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class PlantController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PlantController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<Plant> plants = await _context.Plants.Include(p => p.PlantImages).ToListAsync();
            return View(plants);
        }
        public async Task<IActionResult> Create()
        {
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();

            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Create(Plant plant)
        {
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();
           
            if (!ModelState.IsValid) return View();
            if (plant.MainImage == null || plant.AnotherImages == null)
            {
                ModelState.AddModelError("", "Please, choose main image or another image");
                return View();
            }
            if (!plant.MainImage.IsOkay(1))
            {
                ModelState.AddModelError("MainImage", "Please, choose image file and max 1Mb");
                return View();
            }
            foreach (var image in plant.AnotherImages)
            {
                if (!image.IsOkay(1))
                {
                    ModelState.AddModelError("AnotherImage", "Please, choose image file and max 1Mb");
                    return View();
                }
            }

            plant.PlantImages = new List<PlantImage>();

            PlantImage mainImage = new PlantImage
            {
                ImagePath = await plant.MainImage.FileCreate(_env.WebRootPath, @"assets\images\website-images"),
                IsMain = true,
                Plant = plant
            };

            plant.PlantImages.Add(mainImage);
            foreach (var image in plant.AnotherImages)
            {
                PlantImage another = new PlantImage
                {
                    ImagePath = await image.FileCreate(_env.WebRootPath, @"assets\images\website-images"),
                    IsMain = false,
                    Plant = plant
                };
                plant.PlantImages.Add(another);
            }
            plant.PlantCategories = new List<PlantCategory>();

            foreach (var id in plant.CategoryIds)
            {
                PlantCategory plantCategory = new PlantCategory
                {
                    Plant = plant,
                    CategoryId = id
                };
                plant.PlantCategories.Add(plantCategory);
            }

            await _context.Plants.AddAsync(plant);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();

            Plant plant = await _context.Plants.Include(p=>p.PlantImages).Include(p=>p.PlantCategories).FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            return View(plant);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Edit(int id, Plant plant)
        {
            ViewBag.Colors = await _context.Colors.ToListAsync();
            ViewBag.Sizes = await _context.Sizes.ToListAsync();
            ViewBag.Categories = await _context.Categories.ToListAsync();

            Plant existed = await _context.Plants.Include(p => p.PlantImages).Include(p=>p.PlantCategories).FirstOrDefaultAsync(p=>p.Id==id);
            if (existed == null) return NotFound();
            if (plant.ImageIds == null && plant.AnotherImages == null)
            {
                ModelState.AddModelError("", "It is not possible to delete another images without adding a new one!");
                return View(existed);
            }
            if (plant.ImageId == null && plant.MainImage == null)
            {
                ModelState.AddModelError("", "It is not possible to delete another images without adding a new one!");
                return View(existed);
            }
            List<PlantImage> removeableImages;
            if (plant.ImageIds != null)
            {
                removeableImages = existed.PlantImages.Where(p => p.IsMain == false && !plant.ImageIds.Contains(p.Id)).ToList();
            }
            else
            {
                removeableImages = existed.PlantImages.Where(p=>p.IsMain == false).ToList();
            }

            
            existed.PlantImages.RemoveAll(p => removeableImages.Any(ri => ri.Id == p.Id));


            List<PlantCategory> removeableCategories = existed.PlantCategories.Where(pc => !plant.CategoryIds.Contains(pc.CategoryId)).ToList();
            existed.PlantCategories.RemoveAll(pc => removeableCategories.Any(rc => rc.Id == pc.Id));
            foreach (var item in plant.CategoryIds)
            {
                PlantCategory existedCategory = existed.PlantCategories.FirstOrDefault(pc => pc.CategoryId == item);
                if (existedCategory == null)
                {
                    PlantCategory plantCategory = new PlantCategory
                    {
                        PlantId = existed.Id,
                        CategoryId = item
                    };
                    existed.PlantCategories.Add(plantCategory);
                }
            }
            if (plant.ImageId == null)
            {
                PlantImage removeableImage = existed.PlantImages.FirstOrDefault(p => p.IsMain == true);

                if(removeableImage != null)
                {

                    existed.PlantImages.Remove(removeableImage);
                    FileUtilities.FileDelete(_env.WebRootPath, @"assets\images\website-images", removeableImage.ImagePath);
                }
                       
            }
            foreach (var image in removeableImages)
            {
                FileUtilities.FileDelete(_env.WebRootPath, @"assets\images\website-images", image.ImagePath);
            }

            if (plant.MainImage != null)
            {
                    PlantImage mainPlantImage = new PlantImage
                    {
                        ImagePath = await plant.MainImage.FileCreate(_env.WebRootPath, @"assets\images\website-images"),
                        IsMain = true,
                        PlantId = existed.Id
                    };
                    existed.PlantImages.Add(mainPlantImage);
            }
           
            if (plant.AnotherImages != null)
            {
                foreach (var image in plant.AnotherImages)
                {
                    PlantImage plantImage = new PlantImage
                    {
                        ImagePath = await image.FileCreate(_env.WebRootPath, @"assets\images\website-images"),
                        IsMain = false,
                        PlantId = existed.Id
                    };
                    existed.PlantImages.Add(plantImage);
                }
            }
            _context.Entry(existed).CurrentValues.SetValues(plant);
            
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Detail(int id)
        {
            Plant plant = await _context.Plants.Include(p => p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            return View(plant);
        }
        public async Task<IActionResult> Delete(int id)
        {
            Plant plant = await _context.Plants.Include(p=>p.PlantImages).FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            return View(plant);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePlant(int id)
        {
            Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            if (plant == null) return NotFound();
            _context.Plants.Remove(plant);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pronia/Controllers/PlantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Pronia.DAL;
using Pronia.Models;
using Pronia.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Controllers
{
    public class PlantController : Controller
    {
        private readonly AppDbContext _context;

        public PlantController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int page=1)
        {
            var query =  _context.Plants.AsQueryable();
            ViewBag.TotalPage = Math.Ceiling((decimal)await query.CountAsync())/3;
            ViewBag.CurrentPage = page;
            List<Plant> plants = await query.Include(p => p.PlantImages).Skip((page-1)*3).Take(3).ToListAsync();
            return View(plants);
        } 
        public async Task<IActionResult> AddBasket(int id)
        {
            Plant plant = await _context.Plants.FirstOrDefaultAsync(p=>p.Id==id);
            if (plant == null) return NotFound();
            string basketStr = HttpContext.Request.Cookies["Basket"];
            List<BasketCookieItemVM> basket;
         
            if (string.IsNullOrEmpty(basketStr))
            {
                basket = new List<BasketCookieItemVM>();
                BasketCookieItemVM cookie = new BasketCookieItemVM 
                {
                    Id = plant.Id,
                    Count = 1
                };

                basket.Add(cookie);

                basketStr = JsonConvert.SerializeObject(basket);
               

            }
            else
            {
                basket = JsonConvert.DeserializeObject<List<BasketCookieItemVM>>(basketStr);
                BasketCookieItemVM existedCookie = basket.FirstOrDefault(c => c.Id == plant.Id);
                if (existedCookie == null)
                {
                    BasketCookieItemVM cookie = new BasketCookieItemVM
                    {
                        Id = plant.Id,
                        Count = 1
                    };
                    basket.Add(cookie);
                }
                else
                {
                    existedCookie.Count++;
                }
              
                basketStr = JsonConvert.SerializeObject(basket);
            }
            HttpContext.Response.Cookies.Append("Basket", basketStr);
            
            
            return RedirectToAction("Index","Home");
        }
        public async Task<IActionResult> removeBasket(int id)
        {
            //Plant plant = await _context.Plants.FirstOrDefaultAsync(p => p.Id == id);
            string basketStr = HttpContext.Request.Cookies["Basket"];
            List<BasketCookieItemVM> basket;

            if (!string.IsNullOrEmpty(basketStr))
            {
                basket = JsonConvert.DeserializeObject<List<BasketCookieItemVM>>(basketStr);
                BasketCookieItemVM existedCookie = basket.FirstOrDefault(c => c.Id == id);
                if (existedCookie != null)
                {
                    basket.Remove(existedCookie);
                }

                basketStr = JsonConvert.SerializeObject(basket);


            }
           
            HttpContext.Response.Cookies.Append("Basket", basketStr);
           
            return RedirectToAction("Index", "Home");
        }
        public  IActionResult ShowBasket()
        {
            return Content(HttpContext.Request.Cookies["Basket"]);
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Plant/Create.cshtml
@model Plant
@{
    ViewData["Title"] = "Create";
}
<div asp-validation-summary="ModelOnly" class="alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant price: </label><br />
        <input asp-for="Price" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant description: </label><br />
        <input asp-for="Description" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant skuCode: </label><br />
        <input asp-for="SKUCode" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant shipping: </label><br />
        <input asp-for="Shipping" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant request: </label><br />
        <input asp-for="Request" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Request"></span>
    </div>
    <div>
        <label class="mb-3">Plant guarantee: </label><br />
        <input asp-for="Guarantee" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
    <div>
        <label class="mb-3">Plant colors: </label><br />
        <select class="form-select" asp-for="ColorId" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))"></select>
        <span class="text-danger" asp-validation-for="ColorId"></span>
    </div>
    <div>
        <label class="mb-3">Plant sizes: </label><br />
        <select class="form-select" asp-for="SizeId" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))"></select>
        <span class="text-danger" asp-validation-for="SizeId"></span>
    </div>
    <div>
        <label class="mb-3">Plant categories: </label><br />
        <select class="form-select" asp-for="CategoryIds" asp-items="@(new SelectList(ViewBag.Categories,"Id","Name"))"></select>
        <span class="text-danger" asp-validation-for="CategoryIds"></span>
    </div>
    <div>
        <label class="mb-3">Plant main image: </label><br />
        <input asp-for="MainImage" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="MainImage"></span>
    </div>
    <div>
        <label class="mb-3">Plant another images: </label><br />
        <input asp-for="AnotherImages" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="AnotherImages"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Create plant</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Plant/Delete.cshtml
@model Plant
@{
    ViewData["Title"] = "Delete";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Name: </h4>
        <p>
            @Model.Name
        </p>
    </div>
    <div>
        <h4>Secription: </h4>
        <p>
            @Model.Description
        </p>
    </div>
    <div>
        <h4>Price: </h4>
        <p>
            @Model.Price
        </p>
    </div>
    <div>
        <h4>Size: </h4>
        <p>
            @Model.Size
        </p>
    </div>
    <div>
        <h4>Color: </h4>
        <p>
            @Model.Color
        </p>
    </div>
    <div>
        <h4>Request: </h4>
        <p>
            @Model.Request
        </p>

    </div>
    <div>
        <h4>Guarantee: </h4>
        <p>
            @Model.Guarantee
        </p>

    </div>
    <div>
        <h4>Shipping: </h4>
        <p>
            @Model.Shipping
        </p>

    </div>
    <div>
        <h4>SKUCode: </h4>
        <p>
            @Model.SKUCode
        </p>

    </div>
    <div>
        <h4>Main Image: </h4>
        <img style="width:150px; height:150px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p => p.IsMain == true)?.ImagePath" alt="Product Images" />
    </div>
    <div>
        <h4>Another Images: </h4>
        <img style="width:150px; height:150px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p => p.IsMain == false)?.ImagePath" alt="Product Images" />

    </div>
</div>
<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Pronia/Areas/ProniaAdmin/Views/Plant/Detail.cshtml
@model Plant
@{
    ViewData["Title"] = "Detail";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Name: </h4>
        <p>
            @Model.Name
        </p>
    </div>
    <div>
        <h4>Description: </h4>
        <p>
            @Model.Description
        </p>
    </div>
    <div>
        <h4>Price: </h4>
        <p>
            @Model.Price
        </p>
    </div>
    <div>
        <h4>SkuCode: </h4>
        <p>
            @Model.SKUCode
        </p>
    </div>
    <div>
        <h4>Shipping: </h4>
        <p>
            @Model.Shipping
        </p>
    </div>
    <div>
        <h4>Request: </h4>
        <p>
            @Model.Request
        </p>
    </div>
    <div>
        <h4>Guarantee: </h4>
        <p>
            @Model.Guarantee
        </p>
    </div>
    <div>
        <h4>Main Image: </h4>
        <img style="width:150px; height:150px;" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(p => p.IsMain == true).ImagePath" alt="Product Images" />
    </div>
    <div>
        <h4>Another Images: </h4>
        @foreach (var image in Model.PlantImages)
        {
            <img style="width:150px; height:150px;"  src="~/assets/images/website-images/@image.ImagePath" alt="Product Images" />
        }
    </div>

</div>

Pronia/Areas/ProniaAdmin/Views/Plant/Edit.cshtml
@model Plant
@{
    ViewData["Title"] = "Create";
}
<div asp-validation-summary="ModelOnly" class="alert-danger"></div>
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Plant name: </label><br />
        <input asp-for="Name" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div>
        <label class="mb-3">Plant price: </label><br />
        <input asp-for="Price" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Price"></span>
    </div>
    <div>
        <label class="mb-3">Plant description: </label><br />
        <input asp-for="Description" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div>
        <label class="mb-3">Plant skuCode: </label><br />
        <input asp-for="SKUCode" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SKUCode"></span>
    </div>
    <div>
        <label class="mb-3">Plant shipping: </label><br />
        <input asp-for="Shipping" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Shipping"></span>
    </div>
    <div>
        <label class="mb-3">Plant request: </label><br />
        <input asp-for="Request" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Request"></span>
    </div>
    <div>
        <label class="mb-3">Plant guarantee: </label><br />
        <input asp-for="Guarantee" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Guarantee"></span>
    </div>
    <div>
        <label class="mb-3">Plant colors: </label><br />
        <select class="form-select" asp-for="ColorId" asp-items="@(new SelectList(ViewBag.Colors,"Id","Name"))"></select>
        <span class="text-danger" asp-validation-for="ColorId"></span>
    </div>
    <div>
        <label class="mb-3">Plant sizes: </label><br />
        <select class="form-select" asp-for="SizeId" asp-items="@(new SelectList(ViewBag.Sizes,"Id","Name"))"></select>
        <span class="text-danger" asp-validation-for="SizeId"></span>
    </div>
    <div>
        <label class="mb-3">Plant categories: </label><br />
        <select class="form-select" asp-for="CategoryIds">
            @foreach (Category category in ViewBag.Categories)
            {
                if (Model.PlantCategories.FirstOrDefault(pc => pc.CategoryId == category.Id) != null)
                {
                    <option value="@category.Id" selected>@category.Name</option>
                }
                else
                {
                    <option value="@category.Id">@category.Name</option>
                }
            }
        </select>
        <span class="text-danger" asp-validation-for="CategoryIds"></span>
    </div>
    <div>
        <label class="mb-3">Plant main image: </label><br />
        <input asp-for="MainImage" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="MainImage"></span>
    </div>
    <div>
        <label class="mb-3">Plant another images: </label><br />
        <input asp-for="AnotherImages" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="AnotherImages"></span>
    </div>



    <div>
        <div class="d-flex">
            <div class="col-lg-2" style="position:relative;">
                <label class="mb-3">Plant main image: </label><br />
                <i class="mdi mdi-close closeBtn" style="position:absolute;top:10px;right:5px;color:red;font-size:20px;"></i>
                <img style="width:100%; height:150px" src="~/assets/images/website-images/@Model.PlantImages.FirstOrDefault(i => i.IsMain == true)?.ImagePath" />
                <input type="hidden" value="@Model.PlantImages.FirstOrDefault(i => i.IsMain == true)?.Id" name="ImageId" />
            </div>
        </div>

    </div>
    <span>Plant another images</span><br />
    <div>
        <div class="d-flex">
            @foreach (var image in Model.PlantImages.Where(i => i.IsMain == false))
            {
                <div class="col-lg-3" style="position:relative;">
                    <i class="mdi mdi-close closeBtn" style="position:absolute;top:10px;right:5px;color:red;font-size:20px;"></i>
                    <img style="width:100%; height:150px" src="~/assets/images/website-images/@image.ImagePath" />
                    <input type="hidden" value="@image.Id" name="ImageIds" />
                </div>
            }
        </div>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Edit plant</button>
    </div>
</form>
@section Scripts{
    <script>
        $(".closeBtn").click(function () {
            this.parentNode.remove();
        })
    </script>
}

Pronia/Areas/ProniaAdmin/Views/Plant/Index.cshtml
@model List<Plant>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a asp-controller="Plant" asp-action="Create" style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create plant</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Name
                </th>
                <th>
                    Price
                </th>
                <th>
                    Color
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Plant plant in Model)
            {
                <tr>
                    <td>
                        <img style="width:150px; height:150px" src="~/assets/images/website-images/@plant.PlantImages.FirstOrDefault(i => i.IsMain == true)?.ImagePath" />
                    </td>
                    <td>
                        @plant.Name
                    </td>
                    <td>
                        $@plant.Price
                    </td>

                    <td>
                        @plant.Color
                    </td>
                    <td>
                        <div class="d-flex">
                            <div class="detail">
                                <a asp-controller="Plant" asp-action="Detail" asp-route-id="@plant.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                            </div>
                            <div class="ms-2 edit">
                                <a asp-controller="Plant" asp-action="Edit" asp-route-id="@plant.Id" class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                            </div>
                            <div class="ms-2 delete">
                                <a asp-controller="Plant" asp-action="Delete" asp-route-id="@plant.Id" class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                            </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>
    </table>
</div>