Pronia/Models/Slider.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Image { get; set; }
        [StringLength(maximumLength:30)]
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public byte Discount { get; set; }
        public byte Order { get; set; }
        public string DiscoverUrl { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
    }
}

Pronia/Areas/ProniaAdmin/Controllers/SliderController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Pronia.DAL;
using Pronia.Extensions;
using Pronia.Models;
using Pronia.Utilities;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Pronia.Areas.ProniaAdmin.Controllers
{
    [Area("ProniaAdmin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SliderController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            List<Slider> sliders = await _context.Sliders.ToListAsync();
            return View(sliders);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider)
        {
            if (!ModelState.IsValid) return View();
            if (slider.Photo != null)
            {
                
                if (slider.Photo.IsOkay(1))
                {
                    ModelState.AddModelError("Photo", "Please, choose image file which size under 1 Mb");
                    return View();
                }
               
                slider.Image = await slider.Photo.FileCreate(_env.WebRootPath, @"assets\images\website-images");
                await _context.Sliders.AddAsync(slider);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ModelState.AddModelError("Photo", "Please, choose file");
                return View();
            }
           
        }
        public async Task<IActionResult> Detail(int id)
        {
            Slider slider = await _context.Sliders.FirstOrDefaultAsync(s=>s.Id==id);
            if (slider == null) return NotFound();
            
            return View(slider);
        }
        public async Task<IActionResult> Edit(int id)
        {
            Slider slider =  await _context.Sliders.FirstOrDefaultAsync(s=>s.Id==id);
            if (slider==null)
            {
                return NotFound();
            }
            return View(slider);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, Slider slider)
        {
            if (!ModelState.IsValid)
            {
                return View(slider);
            }
            Slider existedSlider = await _context.Sliders.FirstOrDefaultAsync(s => s.Id == id);
            if (slider.Photo !=null)
            {
                if (!slider.Photo.IsOkay(1))
                {
                    string path = _env.WebRootPath + @"\assets\images\website-images\" + existedSlider.Image;
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    existedSlider.Image = await slider.Photo.FileCreate(_env.WebRootPath, @"assets\images\website-images");

                }
                else
                {
                    ModelState.AddModelError("Photo", "Selected image is not valid!");
                    return View(slider);
                }
            }
            existedSlider.Title = slider.Title;
            existedSlider.SubTitle = slider.SubTitle;
            existedSlider.Discount = slider.Discount;
            existedSlider.DiscoverUrl = slider.DiscoverUrl;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }
        public async Task<IActionResult> Delete(int id)
        {
            Slider slider = await _context.Sliders.FirstOrDefaultAsync(s=>s.Id==id);
            if (slider == null) return NotFound();
           
            return View(slider);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteSlider(int id)
        {
            Slider slider = await _context.Sliders.FirstOrDefaultAsync(s => s.Id == id);
            if (slider == null) return NotFound();
            _context.Sliders.Remove(slider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Pronia/Areas/ProniaAdmin/Views/Slider/Create.cshtml
@model Slider
@{
    ViewData["Title"] = "Create";
}
<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Slider title: </label><br />
        <input asp-for="Title" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div>
        <label class="mb-3">Slider Subtitle: </label><br />
        <input asp-for="SubTitle" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SubTitle"></span>
    </div>
    <div>
        <label class="mb-3">Slider discount: </label><br />
        <input asp-for="Discount" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Discount"></span>
    </div>
    <div>
        <label class="mb-3">Slider discover url: </label><br />
        <input asp-for="DiscoverUrl" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="DiscoverUrl"></span>
    </div>
    <div>
        <label class="mb-3">Slider image: </label><br />
        <input asp-for="Photo" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Photo"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Create slider</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Slider/Delete.cshtml
@model Slider
@{
    ViewData["Title"] = "Delete";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Title: </h4>
        <p>
            @Model.Title
        </p>
    </div>
    <div>
        <h4>Subtitle: </h4>
        <p>
            @Model.SubTitle
        </p>
    </div>
    <div>
        <h4>Discount: </h4>
        <p>
            @Model.Discount
        </p>
    </div>
    <div>
        <h4>DiscoverUrl: </h4>
        <p>
            @Model.DiscoverUrl
        </p>
    </div>
    <div>
        <h4>Image: </h4>
        <img style="width:150px;" src="~/assets/images/website-images/@Model.Image" />
    </div>
</div>
<form method="post" class="mt-4">
    <button type="submit" class="btn btn-danger">Delete</button>
</form>

Pronia/Areas/ProniaAdmin/Views/Slider/Detail.cshtml
@model Slider
@{
    ViewData["Title"] = "Detail";
}
<div>
    <div>
        <h4>Id: </h4>
        <p>
            @Model.Id
        </p>
    </div>
    <div>
        <h4>Title: </h4>
        <p>
            @Model.Title
        </p>
    </div>
    <div>
        <h4>Subtitle: </h4>
        <p>
            @Model.SubTitle
        </p>
    </div>
    <div>
        <h4>Discount: </h4>
        <p>
            @Model.Discount
        </p>
    </div>
    <div>
        <h4>DiscoverUrl: </h4>
        <p>
            @Model.DiscoverUrl
        </p>
    </div>
    <div>
        <h4>Image: </h4>
        <img style="width:100px"  src="~/assets/images/website-images/@Model.Image"/>
    </div>
</div>

Pronia/Areas/ProniaAdmin/Views/Slider/Edit.cshtml
@model Slider
@{
    ViewData["Title"] = "Edit";
}

<form method="post" enctype="multipart/form-data">
    <div>
        <label class="mb-3">Slider title: </label><br />
        <input asp-for="Title" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Title"></span>
    </div>
    <div>
        <label class="mb-3">Slider Subtitle: </label><br />
        <input asp-for="SubTitle" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="SubTitle"></span>
    </div>
    <div>
        <label class="mb-3">Slider discount: </label><br />
        <input asp-for="Discount" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="Discount"></span>
    </div>
    <div>
        <label class="mb-3">Slider discover url: </label><br />
        <input asp-for="DiscoverUrl" class="form-control" /><br />
        <span class="text-danger" asp-validation-for="DiscoverUrl"></span>
    </div>
    <div>
        <label class="mb-3">Slider image: </label><br />
        <input asp-for="Photo" class="form-control" accept="image/*" /><br />
        <span class="text-danger" asp-validation-for="Photo"></span>
    </div>
    <div class="mt-3">
        <button type="submit" class="btn btn-primary">Edit slider</button>
    </div>
</form>

Pronia/Areas/ProniaAdmin/Views/Slider/Index.cshtml
@model List<Slider>
@{
    ViewData["Title"] = "Index";
}
<div class="table-responsive pt-3">
    <a asp-controller="Slider" asp-action="Create" style="color:white; font-size:20px;" class="my-2 btn btn-lg btn-success">Create slider</a>
    <table class="table table-dark">
        <thead>
            <tr>
                <th>
                    Image
                </th>
                <th>
                    Title
                </th>
                <th>
                    Subtitle
                </th>
                <th>
                    Discount
                </th>
                <th>
                    Settings
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Slider slider in Model)
            {
            <tr>
                <td>
                    <img style="width:150px; height:150px" src="~/assets/images/website-images/@slider.Image" />
                </td>
                <td>
                    @slider.Title
                </td>
                <td>
                    @if (slider.SubTitle.Length >= 30)
                    {
                        @(slider.SubTitle.Substring(0, 30).ToString() + "...")
                    }
                    else
                    {
                        @slider.SubTitle
                    }
                </td>

                <td>
                    @slider.Discount
                </td>
                <td>
                    <div class="d-flex">
                        <div class="detail">
                            <a asp-controller="Slider" asp-action="Detail" asp-route-id="@slider.Id" class="btn btn-outline-primary"><i class="mdi mdi-details"></i></a>
                        </div>
                        <div class="ms-2 edit">
                            <a asp-controller="Slider" asp-action="Edit" asp-route-id="@slider.Id" class="btn btn-outline-warning"><i class="mdi mdi-refresh"></i></a>
                        </div>
                        <div class="ms-2 delete">
                            <a asp-controller="Slider" asp-action="Delete" asp-route-id="@slider.Id" class="btn btn-outline-danger"><i class="mdi mdi-delete-forever"></i></a>
                        </div>
                    </div>
                </td>
            </tr>
            }

        </tbody>
    </table>
</div>